FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace

COPY pom.xml .
COPY backend/pom.xml backend/pom.xml
COPY backend/src backend/src

RUN mvn -B -DskipTests -pl backend -am clean package

FROM eclipse-temurin:21-jre
WORKDIR /work
COPY --from=build /workspace/backend/target/quarkus-app/ /work/quarkus-app/
EXPOSE 8080
CMD ["java","-jar","/work/quarkus-app/quarkus-run.jar"]
